name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fix image name
        run: |
          IMAGE_NAME=$(echo "$ECR_REPOSITORY" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME FIXED: [$IMAGE_NAME]"

      - name: Debug variables
        run: |
          echo "AWS_REGION=[$AWS_REGION]"
          echo "AWS_ACCOUNT_ID=[$AWS_ACCOUNT_ID]"
          echo "ECR_REPOSITORY ORIGINAL=[$ECR_REPOSITORY]"
          echo "IMAGE_NAME FIXED=[$IMAGE_NAME]"
          echo "ECS_CLUSTER=[$ECS_CLUSTER]"
          echo "ECS_SERVICE=[$ECS_SERVICE]"

      - name: Test AWS
        run: aws sts get-caller-identity

      - name: Login ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY ./src/AtlasCommerce
        
      - name: Verify local image docker
        run: docker images

      - name: Tag Docker image
        run: |
          FULL_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
          echo "FROM: $IMAGE_NAME:latest"
          echo "TO: $FULL_IMAGE"
          docker tag $IMAGE_NAME:latest $FULL_IMAGE

      - name: Push Docker image
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

      - name: TEST REAL ECS
        run: |
          aws ecs describe-services --cluster atlas-cluster --services atlas-task-service-yj758x09
      - name: Deploy ECS
        run: |
          aws ecs update-service \
          --region us-east-1 \
          --cluster atlas-cluster \
          --service atlas-task-service-yj758x09 \
          --force-new-deployment
        
      - name: Deploy to ECS
        run: aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment

      - name: Wait for ECS deployment
        run: aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE

      - name: Check ECS status
        run: aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE